apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: smart-workshop
  labels:
    app: api
spec:
  type: LoadBalancer
  selector:
    app: api
  ports:
  - name: http
    port: 5180
    targetPort: 5180
    protocol: TCP
  sessionAffinity: None
